### PR TITLE
alter soft match

### PR DESCRIPTION
**Pull request by DanielSunami**
Soft Match now matches any word in predefined rule, the following example would be allowed:

Predefined rule: Math Geo History
User field: English,Math

### CODE REVIEW

**Comment by bobopinna** [comment]
We need to use a different way to do it.
What's the result if a field contains several words with spaces and we set as filter some of that words.
For what I understand, you can do the same thing you want without code changes by adding several autoenrol instances to a course. Each instance must be set to filter by a different word.

**Comment by nomisge** [comment]
If you use several instances to filter by different words, you wouldn't need the soft-filter option (or at least not in the way I would want to use it). I understood the soft-filter option as a way to have more flexibility within one instance. See issue #20 for more detail.

I suggest supporting filtering by regex and use a regex-group as name for the groups in the course.

**Comment by nomisge** [comment]
Looking at @DanielSunami example, I see following problem when using several instances.

Predefined rule: Math Geo History
User field: English,Math

What if I want all users that have a certain subjects in one group. In this case everyone with "Math, Geo or History" in their user field, should be enroled in the same group?

With several instances, each instance would create their own seperate group: "Math" "Geo", "History"

One solution, if you want to stick with separate instances, would be to have an extra option where you could specify the target groups name. Possible even by regex on the profile field values?

**Comment by bobopinna** [comment]
Now this is solved by new filtering system

**Pull request closed without merging**
